version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: indiegamedev
    ports:
      - 8082:80
    volumes:
      - .:/srv/app
    links:
      - mysql
      - redis
      - mailhog
    environment:
      DB_HOST: mysql
      DB_DATABASE: indiegamedev
      DB_USERNAME: app
      DB_PASSWORD: password
    networks:
      - app-net

  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    volumes:
      - app-db-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: indiegamedev
      MYSQL_USER: app
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - app-net

  redis:
    image: redis:5.0.8-alpine
    ports:
      - 16379:6379
    networks:
      - app-net

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8026:8025
    networks:
      - app-net
  composer: { image: composer/composer, volumes: ['./:/srv/app/', '~/.ssh/:/root/.ssh'], tty: true, working_dir: /srv/app/, command: 'composer install' }

networks:
  app-net:
    driver: bridge

volumes:
  app-db-data: {}
