name: Release New Version to Production
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy to Vapor
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2
          coverage: none
      - name: Validate Composer
        run: composer validate
      - name: Install Composer dependencies
        run: |
          composer config "http-basic.nova.laravel.com" "${{ secrets.NOVA_USERNAME }}" "${{ secrets.NOVA_PASSWORD }}"
          composer config "http-basic.spark.laravel.com" "${{ secrets.SPARK_USERNAME }}" "${{ secrets.SPARK_API_TOKEN }}"
          composer install --prefer-dist --no-dev --no-interaction --no-suggest
      - name: Require Vapor CLI
        run: composer global require laravel/vapor-cli --update-no-dev
      - name: Deploy Environment
        env:
          VAPOR_ENV: ${{ 'production' }}
          VAPOR_API_TOKEN: ${{ secrets.VAPOR_API_TOKEN }}
        run: vapor deploy ${{ env.VAPOR_ENV }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Logs
          path: ./storage/logs
      - name: Sentry Release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment:
            production

