<?php

use App\Models\Team;
use Spark\Features;

return [

    /*
    |--------------------------------------------------------------------------
    | Spark Path
    |--------------------------------------------------------------------------
    |
    | This configuration option determines the URI at which the Spark billing
    | portal is available. You are free to change this URI to a value that
    | you prefer. You shall link to this location from your application.
    |
    */

    'path' => 'billing',

    /*
    |--------------------------------------------------------------------------
    | Spark Middleware
    |--------------------------------------------------------------------------
    |
    | These are the middleware that requests to the Spark billing portal must
    | pass through before being accepted. Typically, the default list that
    | is defined below should be suitable for most Laravel applications.
    |
    */

    'middleware' => ['web', 'auth'],

    /*
    |--------------------------------------------------------------------------
    | Branding
    |--------------------------------------------------------------------------
    |
    | These configuration values allow you to customize the branding of the
    | billing portal, including the primary color and the logo that will
    | be displayed within the billing portal. This logo value must be
    | the absolute path to an SVG logo within the local filesystem.
    |
    */

     'brand' =>  [
         //'logo' => realpath(__DIR__.'/../public/svg/billing-logo.svg'),
         'color' => 'bg-blue-500',
     ],

    /*
    |--------------------------------------------------------------------------
    | Proration Behavior
    |--------------------------------------------------------------------------
    |
    | This value determines if charges are prorated when making adjustments
    | to a plan such as incrementing or decrementing the quantity of the
    | plan. This also determines proration behavior if changing plans.
    |
    */

    'prorates' => true,

    /*
    |--------------------------------------------------------------------------
    | Features
    |--------------------------------------------------------------------------
    |
    | Some of Spark's features are optional. You may disable the features by
    | removing them from this array. By removing features from this array
    | you can customize your Spark experience for your own application.
    |
    */

    'features' => [
        // Features::euVatCollection(['home-country' => 'BE']),
        // Features::receiptEmails(['custom-addresses' => true]),
//        Features::paymentNotificationEmails(),
    ],


    /*
    |--------------------------------------------------------------------------
    | Receipt Configuration
    |--------------------------------------------------------------------------
    |
    | The following configuration options allow you to configure the data that
    | appears in PDF receipts generated by Spark. Typically, this data will
    | include a company name as well as your company contact information.
    |
    */

    'receipt_data' => [
        'vendor' => 'Omnia Church Apps',
        'product' => 'Omnia Livestream',
        'street' => '917 SE 6th Court',
        'location' => 'Battle Ground, WA',
        'phone' => '562-396-4896',
    ],

    /*
    |--------------------------------------------------------------------------
    | Spark Billable
    |--------------------------------------------------------------------------
    |
    | Below you may define billable entities supported by your Spark driven
    | application. The Stripe edition of Spark currently only supports a
    | single billable model entity (team, user, etc.) per application.
    |
    | In addition to defining your billable entity, you may also define its
    | plans and the plan's features, including a short description of it
    | as well as a "bullet point" listing of its distinctive features.
    |
    */

    'billables' => [

        'team' => [
            'model' => Team::class,

            'trial_days' => 7,

            'plans' => [
                [
                    'name' => 'Basic',
                    'short_description' => 'This is the basic livestream plan to get you started.',
                    'monthly_id' => env('STRIPE_PLAN_ID_BASIC_MO'),
                    'yearly_id' => env('STRIPE_PLAN_ID_BASIC_YR'),
                    'features' => [
                        'Unlimited Episodes',
                        '90 days of Video Storage',
                        '1 Stream Target (Facebook or YouTube)',
                        'Email/Chat Support',
                        'Free Basic Omnia Sites website ($29/mo value)'
                    ],
                    'yearly_incentive' => '$119/mo',
                    'options' => [
                        'episode_expiration' => 90,
                        \App\Plans\Features\StreamTargetFeature::class => 1,
                    ],
                ],
                [
                    'name' => 'Premium',
                    'short_description' => 'The premium plan is designed to help you grow.',
                    'monthly_id' => env('STRIPE_PLAN_ID_PREMIUM_MO'),
                    'yearly_id' => env('STRIPE_PLAN_ID_PREMIUM_YR'),
                    'features' => [
                        'Unlimited Episodes',
                        '6 Months of Video Storage',
                        '3 Stream Targets (Facebook, YouTube, etc.)',
                        'Phone/Email/Chat Support',
                        'Free Basic Omnia Sites website ($29/mo value)',
                        'API Integrations',
                    ],
                    'yearly_incentive' => '$149/mo',
                    'options' => [
                        'episode_expiration' => 182,
                        \App\Plans\Features\StreamTargetFeature::class => 3,
                    ],
                ],
            ],
        ],
    ]
];
